export const queryKeys = {
  user: 'user',
  admin: 'admin',
  users: 'users',
  instructor: 'instructor',
  courses: 'courses',
  course: 'course',
  videos: 'videos',
  video: 'video',
  reviews: 'reviews',
  review: 'review',
  categories: 'categories',
  category: 'category',
  subCategories: 'subCategories',
  subCategory: 'subCategory',
  lessons: 'lessons',
  lesson: 'lesson',
  assignments: 'assignments',
  me: 'me',
  usersRole: 'usersRole',
};
